Milestone2 of Calculator React Solo Project
carlosprietobarron/calculator pull request #3
Opened 2021-01-11 12:40 UTC by carlosprietobarron

In this milestone : 

Create Display component

Create Button Panel component and button components

2021-01-11 13:06 UTC, rOluochKe requested changes
Hello @carlosprietobarron
### You have done well so far :clap: However, you have a few issues to fix:-
- [ ] Add linting files as recommended by Microverse, install all the required dependencies, configure them well and run commands `npx eslint .` and `npx stylelint "**/*.{css,scss}"` If errors kindly solve them. [Follow this guide](https://github.com/microverseinc/linters-config/tree/master/react-redux)
- [ ] We recommend the use of es6 arrow functions rather than the function keyword. See example `const Btngroup = (props) => { # Your code }`
- [ ] The script `npm start` is not working, this is required to start the app in the app. See image below
![npm start](https://user-images.githubusercontent.com/8114528/104186108-f7558700-5426-11eb-8edc-1315ff0c12b0.png)
- [ ] Remove unwanted files like App.test.js and setupTests.js
- [ ] Files like App.js is to be added in the directory components
### Make all these changes and submit for another code review. Good luck.
- Happy coding!

2021-01-12 00:08 UTC, mikenath223 requested changes
### Hello @carlosprietobarron  👋

**Good job on this. The project is almost in the clear.**

Just a change to be made.

- Please refer to the comment on the code.

### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2021-01-12 00:10 UTC, mikenath223 commented on .eslintrc.json
> +  //"extends": ["airbnb", "plugin:react/recommended"],
- [ ] Kindly uncomment this. You should use config rules shared by other students. And that line is one of the required rules.

2021-01-12 00:13 UTC, mikenath223 commented on src/components/display.js
> +/* eslint-enable react/prop-types, no-console, arrow-body-style */
- [ ] Please add proptype validation here.

2021-01-12 00:14 UTC, mikenath223 commented on src/components/btnPanel.js
> +export default ButtonPanel;
- [ ] Kindly also add proptypes validation here

2021-01-12 00:15 UTC, mikenath223 commented on src/components/Buttn.js
> +/* eslint-enable react/prop-types, no-console, arrow-body-style */
- [ ] Please add proptypes validation here.

2021-01-12 00:18 UTC, mikenath223 commented
- I think you made the mistake of requesting a review on milestone1 when you actually might have wanted to request a review on milestone2 branch instead. If this isn't the case then kindly make these changes. But otherwise, make the changes on the correct branch.

2021-01-13 02:14 UTC, bellom approved these changes
## Hi @carlosprietobarron  :clap: 

**Great work making all the necessary corrections from the previous review.**

# Status: Approved 👍 

**NOTE:**_Few things you should look into before merging or moving to the next milestone;_

**1.** For some reason you added Node server, please you don't need this.
Please let's carefully read and follow the instructions in the pathwright as we both know all Microverse students are bind to follow the project requirements and instructions.

**2.** Let's be professional with the naming of our feature-branch. Kindly name your branch according to the milestone you're working on.
In your case instead of using `milestone1`, you're working on `milestone2`, you should have named your branch `milestone2`.

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2021-01-13 22:35 UTC, closed without merging